project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "PolOpt Carbon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



