name: polopt-carbon
channels:
  - conda-forge
  - nodefaults

dependencies:
  # Core Python
  - python =3.11

  # Geospatial stack
  - geopandas >=0.14
  - rasterio >=1.3
  - rioxarray >=0.15
  - pyproj >=3.5
  - shapely >=2.0
  - fiona
  - gdal

  # Numeric + data handling
  - numpy >=1.24
  - pandas >=2.0
  - xarray
  - pyarrow

  # CLI and utilities
  - typer >=0.12
  - click
  - rich

  # Dev / testing (optional but useful)
  - pytest
  - black
  - isort

  # Ensure C library consistency
  - proj
  - geos
  - sqlite
